<?php

namespace gestioneventBundle\Repository;

/**
 * eventcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class guideRepository extends \Doctrine\ORM\EntityRepository
{
}
